// <auto-generated />
using MenuDigitalTPWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MenuDigitalTPWeb.Migrations
{
    [DbContext(typeof(MenuDigitalTPWebContext))]
    [Migration("20251201183541_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("MenuDigitalTPWeb.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vinos"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Espumantes"
                        });
                });

            modelBuilder.Entity("MenuDigitalTPWeb.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Descuento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Un Malbec intenso con notas de ciruela y madera.",
                            Descuento = 10,
                            ImageUrl = "https://ejemplo.com/malbec.jpg",
                            Name = "Malbec Reserva",
                            Price = "8500.00M",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Aromas a frutos rojos y un toque especiado.",
                            Descuento = 5,
                            ImageUrl = "https://ejemplo.com/cabernet.jpg",
                            Name = "Cabernet Sauvignon",
                            Price = "9200.00M",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Elegante y seco, con burbujas finas y persistentes.",
                            Descuento = 0,
                            ImageUrl = "https://ejemplo.com/champagne.jpg",
                            Name = "Champagne Brut Nature",
                            Price = "11500.00M",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("MenuDigitalTPWeb.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BioImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BioImageUrl = "https://ejemplo.com/bio.jpg",
                            Description = "Apasionado por los vinos y la buena atención.",
                            Email = "luis@ejemplo.com",
                            FirstName = "Luis",
                            ImageUrl = "https://ejemplo.com/imagen.jpg",
                            LastName = "Pérez",
                            LocalName = "Vinoteca Don Luis",
                            Password = "12345"
                        });
                });

            modelBuilder.Entity("MenuDigitalTPWeb.Entities.Category", b =>
                {
                    b.HasOne("MenuDigitalTPWeb.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MenuDigitalTPWeb.Entities.Product", b =>
                {
                    b.HasOne("MenuDigitalTPWeb.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenuDigitalTPWeb.Entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MenuDigitalTPWeb.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MenuDigitalTPWeb.Entities.User", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
